# Generated by Django 4.1.7 on 2023-03-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=200, unique=True)),
                ('balance', models.FloatField()),
                ('customer_name', models.CharField(max_length=200)),
                ('account_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=200, unique=True)),
                ('amount', models.FloatField()),
                ('transaction_type', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_API.account')),
            ],
        ),
    ]
