# Generated by Django 4.1.7 on 2023-03-08 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='account',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
