# Generated by Django 4.1.7 on 2023-03-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_API', '0002_account_account_creation_account_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('SAV', 'Savings'), ('CHK', 'Checking')], max_length=200),
        ),
    ]
