# Generated by Django 4.1.7 on 2023-03-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_API', '0003_alter_account_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_update',
            field=models.DateTimeField(),
        ),
    ]
