# Generated by Django 4.1.2 on 2023-03-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_API', '0004_alter_account_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
