# Generated by Django 4.1.2 on 2023-03-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_API', '0005_alter_account_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Savings', 'Savings'), ('Checking', 'Checking')], max_length=200),
        ),
    ]
