# Generated by Django 4.1.2 on 2023-03-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_API', '0007_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=200),
        ),
    ]
