# Generated by Django 4.1.2 on 2023-03-09 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_API', '0009_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.CharField(default='Init', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='sucess', max_length=200),
            preserve_default=False,
        ),
    ]
