# Generated by Django 4.1.2 on 2023-03-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_API', '0010_transaction_description_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
